# gRPC server settings
grpc.server.port=59091

# Kafka settings
kafka.bootstrap-servers=localhost:9092
kafka.topic.sensors=telemetry.sensors.v1
kafka.topic.hubs=telemetry.hubs.v1


# Server port
server.port=8080

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration